apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: secretli-ui-route
  namespace: secretli
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`patrickscheid.de`) && PathPrefix(`{{ trimSuffix "/" .Values.forwardedPrefix }}`)
      kind: Rule
      services:
        - name: secretli-ui
          port: 80
  tls:
    secretName: patrickscheid.de-cert-secret
