name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project code
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and publish to Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{github.repository }}:${{ github.sha }}

  deploy:
    name: Deploy to kubernetes cluster
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          exec: >-
            helm upgrade
            --install
            --namespace secretli
            --set imageVersion=${{ github.sha }}
            --values ./chart/production.yaml
            secretli-ui
            ./chart
